version: "3"
services:
  varga-dev: #just put any name
    build:
      context: ./ #current directory
      dockerfile: Dockerfile.dev #any docker file name  like for Dockerfile.prod
      args:
        - NODE_ENV=development
    restart: always
    container_name: api-dev
    volumes:
      - ./src:/app/src
    ports:
      - "4040:4040"
    environment:
      - NODE_ENV=development
      - SERVER_TYPE=testing
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
